# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc.aiplatform.v1 import chat_pb2 as app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc/aiplatform/v1/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiPlatformStub:
    """AiPlatform 是 AI 侧的内网服务。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/aiplatform.v1.AiPlatform/Chat',
                request_serializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/aiplatform.v1.AiPlatform/ChatStream',
                request_serializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatEvent.FromString,
                _registered_method=True)


class AiPlatformServicer:
    """AiPlatform 是 AI 侧的内网服务。
    """

    def Chat(self, request, context):
        """Chat 一次完整的非流式对话（docs/04-§2.2 的 `POST /chat`）。

        与 HTTP `POST /chat` **行为等价**（含 `use_tools=true` 时转 Agent 流程），
        两侧的差别只有传输：HTTP 用 `Authorization` 头，gRPC 用同名 metadata。

        MUST NOT 重试（docs/04-§3.4）：会重复计费、重复落上下文。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """ChatStream 一次流式对话（docs/04-§2.2 的 `POST /chat/stream` 的等价物）。

        事件序列（docs/04-§2.3）：`meta` → `reference`* → (`tool_call`/`tool_result`)*
        → `token`* → `usage` → `done`；出错时以 `error` 收尾且**不再有** `usage`/`done`。

        与 HTTP SSE 版本的差别只有传输：HTTP 版把每个事件序列化成
        `event: <名>\ndata: <JSON>\n\n`，这里把同一份数据放进 `ChatEvent` 的 oneof。

        MUST NOT 重试（同上）。客户端取消（断连）时 AI 侧 MUST 停止上游 LLM 调用
        （REQ-ORCH-004 / 其 SRS 的 REQ-CHAT-006）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiPlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiplatform.v1.AiPlatform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiplatform.v1.AiPlatform', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiPlatform:
    """AiPlatform 是 AI 侧的内网服务。
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiplatform.v1.AiPlatform/Chat',
            app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
            app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiplatform.v1.AiPlatform/ChatStream',
            app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
            app_dot_grpc_dot_aiplatform_dot_v1_dot_chat__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
