"""注释规范的机器守门（``docs/15-代码注释规范.md``）。

为什么需要这条测试：注释规范若只写在文档里，三个月后就会退化 —— 本仓库已经吃过
"过时注释比没有注释更危险"的亏（`docs/12-§4.4` 那类问题，最后都是靠注释里的
"为什么"才定位到）。所以把**可机械判定**的那几条钉住：

1. 每个模块（非生成物）必须有 docstring —— 这是"模块职责"唯一的落点；
2. ``app/`` 的公共类/方法必须有 docstring，**除** §3 明确豁免的两类
   （平凡取值器；已文档化端口的实现类 —— 契约在端口，重复一遍只会多一处要同步的地方）；
3. 不允许**无主 TODO/FIXME/XXX/HACK**（必须带负责人/日期/issue）；
4. 不允许**注释掉的代码**（去掉 ``#`` 后能被 ``ast.parse`` 的实现语句）；
5. 单字动词标签（``# 调用``、``# 创建``…）**只能**出现在 ``# ----`` 分节线之间，
   不允许散落在代码上方当"复述式注释"。

刻意**不**判定：docstring 的措辞质量、`Args/Returns` 是否齐全、注释与代码是否仍然一致 ——
那些要么不可判定、要么会把有用的说明逼成模板句。它们靠 code review 与 `docs/15` §2。
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
APP = PROJECT_ROOT / "app"
TESTS = PROJECT_ROOT / "tests"

#: 生成物：由 `tools/gen_grpc_stubs.ps1` 产出，重新生成会覆盖（`docs/15` §3.4）
GENERATED_MARKERS = (
    "Generated by the Protocol Buffer compiler",
    "Generated by the gRPC Python protocol compiler",
    "Generated package -- see tools/gen_grpc_stubs.ps1",
    "NO CHECKED-IN PROTOBUF GENCODE",
    "@generated",
)

#: §3.2 豁免：契约写在端口里，实现类只需在类 docstring 里点明端口
PORT_IMPLEMENTATIONS = frozenset(
    {
        # 仓储 / 存储端口
        "InMemoryKnowledgeBaseRepo",
        "MySqlKnowledgeBaseRepo",
        "InMemoryDocumentRepo",
        "MySqlDocumentRepo",
        "InMemoryChunkRepo",
        "MySqlChunkRepo",
        "InMemoryObjectStore",
        "MinioObjectStore",
        "InMemoryConversationStore",
        "RedisConversationStore",
        "InMemoryMemoryRepo",
        "MySqlMemoryRepo",
        "InMemoryMemoryPreferenceStore",
        "InMemoryMemoryVectorIndex",
        # 向量库端口 VectorStore / 任务表端口 TaskStore
        "InMemoryVectorStore",
        "InMemoryTaskStore",
        # 解析器端口 DocumentParser
        "DocxParser",
        "HtmlParser",
        "MarkdownParser",
        "PdfParser",
        "TextParser",
        # 重排端口 Reranker（空实现：行为写在类 docstring 里）
        "IdentityReranker",
        # 标准库 logging 接口（Formatter.format / Filter.filter 由 stdlib 文档定义）
        "ModuleNoiseFilter",
        "JsonFormatter",
        "ConsoleFormatter",
    }
)

#: §3.5：单字动词标签只允许作为分节标题
BARE_LABELS = frozenset(
    {"调用", "创建", "循环", "返回", "设置", "获取", "遍历", "判断", "删除", "更新"}
)
DIVIDER = re.compile(r"^#\s*[-=#*]{4,}\s*$")
TODO_WORD = re.compile(r"\b(TODO|FIXME|XXX|HACK)\b")
TODO_OWNER = re.compile(
    r"(@\w+|[\w.\-]+@[\w.\-]+|\d{4}-\d{2}-\d{2}|#\d+|issue|GH-\d+|PR-\d+)", re.I
)
CJK = re.compile(r"[\u4e00-\u9fff]")
#: 看起来就是"实现语句"的注释（用于识别注释掉的代码）。
#: 两条分支：① 以语句关键字开头；② 形如 ``name = ...`` / ``obj.attr[k] = ...`` 的赋值。
#: 判别真正的"代码"靠三点同时成立：**无中文** + 能 ``ast.parse`` + 命中本正则 ——
#: 中文散文里出现的 ``=``（如「写入即过期 = 调用方搞错了」）因此不会误报，
#: 而 ``# GET /mcp/servers``（能 parse 成除法）也不会误报。
DEAD_CODE = re.compile(
    r"^(def |class |import |from |return |if |for |while |try:|except |with |@|self\.|await |print\(|assert "
    r"|[\w\.\[\]\"']+\s*(?:\+|-|\*|/)?=\s*\S)"
)


def _sources() -> list[Path]:
    return sorted(p for p in APP.rglob("*.py") if "__pycache__" not in p.parts)


def _test_sources() -> list[Path]:
    return sorted(p for p in TESTS.rglob("*.py") if "__pycache__" not in p.parts)


def _is_generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:8])
    return any(marker in head for marker in GENERATED_MARKERS)


def _is_trivial(node: ast.AST) -> bool:
    """§3.1 豁免：**带 ``@property`` 且无分支、仅一条语句**的取值器。

    刻意要求 ``@property``：最初只看"单语句"就豁免，结果把
    ``def undocumented_public_function(v): return v + 1`` 这种真正的公共函数也放过了
    （合成样本自测时发现的）—— 一个抓不到违规的守门测试比没有测试更糟。
    """
    if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return False
    if not any(
        ast.unparse(decorator).split("(")[0] in {"property", "cached_property"}
        for decorator in node.decorator_list
    ):
        return False
    body = [
        n for n in node.body if not (isinstance(n, ast.Expr) and isinstance(n.value, ast.Constant))
    ]
    if len(body) > 1:
        return False
    return not any(
        isinstance(n, (ast.If, ast.For, ast.While, ast.Try, ast.Match)) for n in ast.walk(node)
    )


def test_every_module_has_a_docstring() -> None:
    """模块 docstring 是"这个文件负责什么"唯一的落点（生成物除外）。"""
    missing = [
        p.relative_to(PROJECT_ROOT).as_posix()
        for p in _sources()
        if not _is_generated(p.read_text(encoding="utf-8"))
        and ast.get_docstring(ast.parse(p.read_text(encoding="utf-8"))) is None
    ]

    assert missing == [], f"以下模块缺 docstring：{missing}"


def test_public_app_api_is_documented() -> None:
    """``app/`` 的公共类与方法必须有 docstring（豁免见模块 docstring 与 ``docs/15`` §3）。"""
    missing: list[str] = []
    for path in _sources():
        text = path.read_text(encoding="utf-8")
        if _is_generated(text):
            continue
        tree = ast.parse(text)
        rel = path.relative_to(PROJECT_ROOT).as_posix()
        for node in tree.body:
            if not isinstance(node, ast.ClassDef) or node.name.startswith("_"):
                continue
            if ast.get_docstring(node) is None:
                missing.append(f"{rel}:{node.lineno} class {node.name}")
            bases = {ast.unparse(base).split(".")[-1] for base in node.bases}
            if (
                node.name in PORT_IMPLEMENTATIONS
                or "BuiltinTool" in bases
                # §3.2：空对象/占位实现（`Null*` / `Unavailable*`）—— 行为就是"照端口签名
                # 报不可用"，逐方法写 docstring 只会重复端口契约；类 docstring 已点明端口。
                or node.name.startswith(("Unavailable", "Null"))
                # §3.2：Protocol 的方法桩（`...`）—— 端口本身的方法，契约在类 docstring。
                or "Protocol" in bases
            ):
                continue
            for sub in node.body:
                if not isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if sub.name.startswith("_") or _is_trivial(sub) or ast.get_docstring(sub):
                    continue
                missing.append(f"{rel}:{sub.lineno} {node.name}.{sub.name}")
        for node in tree.body:
            if isinstance(
                node, (ast.FunctionDef, ast.AsyncFunctionDef)
            ) and not node.name.startswith("_"):
                if _is_trivial(node) or ast.get_docstring(node):
                    continue
                missing.append(f"{rel}:{node.lineno} def {node.name}")

    assert missing == [], "以下公共接口缺 docstring：\n  " + "\n  ".join(missing)


def test_no_unowned_todo() -> None:
    """TODO/FIXME 必须带负责人/日期/issue —— 无主的 TODO 等于没有（``docs/15`` §2/§4）。"""
    offenders: list[str] = []
    for path in _sources():
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            stripped = line.strip()
            if not stripped.startswith("#"):
                continue
            match = TODO_WORD.search(stripped)
            if match and not TODO_OWNER.search(stripped[match.end() :]):
                offenders.append(
                    f"{path.relative_to(PROJECT_ROOT).as_posix()}:{lineno} {stripped[:80]}"
                )

    assert offenders == [], "无主 TODO/FIXME：\n  " + "\n  ".join(offenders)


def test_no_commented_out_code() -> None:
    """注释掉的代码应交给版本控制（``docs/15`` §4）。

    判定要求"去掉 ``#`` 后是一句实现语句"：像 ``# GET /mcp/servers`` 这种
    接口路径标注能被 ``ast.parse`` 当成除法表达式，但**它不是代码**，所以不报。
    """
    offenders: list[str] = []
    for path in _sources():
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            body = line.strip()
            if not body.startswith("#"):
                continue
            body = body.lstrip("#").strip()
            if not body or CJK.search(body) or not DEAD_CODE.match(body):
                continue
            try:
                ast.parse(body)
            except SyntaxError:
                continue
            offenders.append(f"{path.relative_to(PROJECT_ROOT).as_posix()}:{lineno} {body[:70]}")

    assert offenders == [], "疑似注释掉的代码：\n  " + "\n  ".join(offenders)


def test_bare_labels_are_only_section_titles() -> None:
    """``# 调用`` 这类单字标签只能当分节标题，不能当"复述式注释"。"""
    offenders: list[str] = []
    for path in _sources():
        lines = path.read_text(encoding="utf-8").splitlines()
        for index, line in enumerate(lines):
            body = line.strip().lstrip("#").strip()
            if body not in BARE_LABELS:
                continue
            before = lines[index - 1] if index else ""
            after = lines[index + 1] if index + 1 < len(lines) else ""
            if not (DIVIDER.match(before.strip()) and DIVIDER.match(after.strip())):
                offenders.append(
                    f"{path.relative_to(PROJECT_ROOT).as_posix()}:{index + 1} {line.strip()}"
                )

    assert offenders == [], "单字标签出现在非分节位置：\n  " + "\n  ".join(offenders)


def test_test_functions_are_documented() -> None:
    """``tests/`` 里每个 ``test_*`` 都要有一行 docstring 说明**验收点**（``docs/15`` §3.3）。

    刻意**不**要求 fixture 与辅助函数：它们的契约是名字 + 类型标注（`FakeRedis`、
    `_Clock`、`build_servicer_app` 之类），逐个写 docstring 只会产出"返回一个 fake"这种噪音。
    也刻意不检查 docstring 的**措辞质量**（不可判定）—— 只拦"完全没有文档"。
    """
    missing: list[str] = []
    for path in _test_sources():
        text = path.read_text(encoding="utf-8")
        if _is_generated(text):
            continue
        rel = path.relative_to(PROJECT_ROOT).as_posix()
        for node in ast.walk(ast.parse(text)):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if not node.name.startswith("test_") or ast.get_docstring(node):
                continue
            missing.append(f"{rel}:{node.lineno} {node.name}")

    assert missing == [], (
        "以下测试用例缺 docstring（写清它断言的不变量/AC 编号）：\n  "
        + "\n  ".join(sorted(missing))
    )


if __name__ == "__main__":  # pragma: no cover - 便于手工跑
    raise SystemExit(pytest.main([__file__, "-q"]))
