// ai-platform 的 gRPC 契约（网关 → AI，内网调用）。
//
// ============================================================================
// 这是**契约真源**（接缝 J5），两侧都从这一个文件生成代码：
//   - Go 侧：`api/aiplatform/v1/*.pb.go`（网关的 client）
//   - Python 侧：`app/grpc/aiplatform/v1/*_pb2*.py`（AI 的 server）
// 字段名/类型/必填性一旦漂移，两侧的字段级快照测试会直接失败（AC-ORCH-02）。
//
// 为什么真源放在 `ai-platform-go/proto/` 而不是父仓库根：
//   网关是这份契约的所有者（docs/04 是网关的 SRS，AI 侧按其实现），
//   放在网关模块内让「改契约 → 重新生成 → 编译」在同一个模块里完成，
//   不依赖模块外的相对路径。AI 侧的生成脚本显式指向这个文件（见其 tools/）。
//
// 为什么**只**定义 gRPC，不写 `option (google.api.http)`：
//   网关对外是 Gin HTTP/SSE，**不打算**用 kratos 的 HTTP 注解 —— 带上它会让这份
//   契约多依赖 `google/api/annotations.proto`（要额外维护 third_party/），
//   而对外 HTTP 契约的真源是 `docs/02`/`docs/03` 与 Pydantic 模型（OpenAPI）。
//   一份契约只管一个方向，两边都清楚「谁是真源」。
//
// 传输分工（docs/08-§7 的架构决策）：
//   - `Chat` / `ChatStream` 走 gRPC（本文件，M3 落 `Chat`、M4 落 `ChatStream`）；
//   - KB / 文档 / 任务 / 上下文摘要等**纯透传**接口走 HTTP（docs/04-§7）。
// ============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: aiplatform/v1/chat.proto

package aiplatformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AiError 是 AI 侧的错误信封，经 gRPC status details 原样回传（接缝 J2）。
//
// 为什么不是直接靠 gRPC 的状态码：客户端是按 `error.code` 分支的，而多个应用
// 错误码会共用同一个 gRPC 规范码（`UPSTREAM_LLM_ERROR` / `OVERLOADED` 都是
// UNAVAILABLE，`CONTEXT_TOO_LONG` / `QUERY_EMPTY` 都是 INVALID_ARGUMENT）。
// 只靠规范码会让「上下文超限」与「提问为空」在客户端看起来一样。
//
// 为什么 `details` 是 JSON **字符串**而不是 `map<string,string>`：契约里的
// `details` 可以嵌套（`fields` 是数组、`hint` 是对象），展开成扁平 map 会丢结构，
// 而 J2 要求**原样透传**。字符串承载是这里唯一无损的选择。
//
// 这个信封挂在 `google.rpc.Status.details` 里（一个 `Any`），随
// `grpc-status-details-bin` trailer 传输 —— 与 gRPC 生态一致，
// 且 Go 侧 `status.Details()` 能直接解出来。
type AiError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 应用错误码（`INVALID_ARGUMENT` / `CONTEXT_TOO_LONG` / `OVERLOADED` …）。
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 面向用户的文案（zh-CN）。
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// AI 侧希望映射到的 HTTP 状态码：网关直接用它的另一个原因是
	// 「上游说了算」—— 网关自己按码猜状态码会在两侧码表不同步时悄悄改语义。
	HttpStatus int32 `protobuf:"varint,3,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	Retryable  bool  `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// AI 侧的 trace id（接缝 J3）：网关 MUST 原样保留，否则排障时链路断开。
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// `error.details` 的原始 JSON，空表示没有。
	DetailsJson   string `protobuf:"bytes,6,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiError) Reset() {
	*x = AiError{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiError) ProtoMessage() {}

func (x *AiError) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiError.ProtoReflect.Descriptor instead.
func (*AiError) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *AiError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AiError) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *AiError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *AiError) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AiError) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

// ChatMessage 是传给 AI 的一条历史消息。
//
// 只在 `use_memory = false` 时才有值（接缝 J4）：`use_memory = true` 时网关
// MUST NOT 传 history —— AI 从自己的 Redis 取上下文，传了会**重复注入**。
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// system / user / assistant / tool
	Role          string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatRequest 是一次非流式对话的输入。
//
// 字段与 `ai-platform/app/schemas/chat.py::ChatRequest` 逐条对应，**除了**：
//   - 不含 `stream`：gRPC 方法本身就是非流式的，带上它只会出现
//     「HTTP 路径传 true 报 400、gRPC 路径传 true 被忽略」这种行为分叉；
//   - 不含 `user_id`：用户身份来自 `authorization` metadata，由 AI 侧自行验签
//     （接缝 J1/J9）。网关 MUST NOT 自报 user_id 让 AI 信任（防伪造，docs/04-§3.2）。
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户提问，去空白后 1..8000 字符。
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// 会话 ID（`cv_` + ULID）。网关是**唯一生成者**（接缝 J4），MUST 总是填。
	ConversationId *string `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	// use_memory = false 时使用的历史，最多 200 条。
	History []*ChatMessage `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	UseRag  bool           `protobuf:"varint,4,opt,name=use_rag,json=useRag,proto3" json:"use_rag,omitempty"`
	// 知识库过滤，最多 10 个（`kb_` + ULID）。
	KbIds     []string `protobuf:"bytes,5,rep,name=kb_ids,json=kbIds,proto3" json:"kb_ids,omitempty"`
	UseMemory bool     `protobuf:"varint,6,opt,name=use_memory,json=useMemory,proto3" json:"use_memory,omitempty"`
	UseTools  bool     `protobuf:"varint,7,opt,name=use_tools,json=useTools,proto3" json:"use_tools,omitempty"`
	// 覆盖默认模型；须在 AI 侧白名单内。
	Model          *string  `protobuf:"bytes,8,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Temperature    *float64 `protobuf:"fixed64,9,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopK           *int32   `protobuf:"varint,10,opt,name=top_k,json=topK,proto3,oneof" json:"top_k,omitempty"`
	RerankTopN     *int32   `protobuf:"varint,11,opt,name=rerank_top_n,json=rerankTopN,proto3,oneof" json:"rerank_top_n,omitempty"`
	ScoreThreshold *float64 `protobuf:"fixed64,12,opt,name=score_threshold,json=scoreThreshold,proto3,oneof" json:"score_threshold,omitempty"`
	// 埋点透传，不进 Prompt；键值各 ≤ 64 字符。
	Metadata      map[string]string `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatRequest) GetUseRag() bool {
	if x != nil {
		return x.UseRag
	}
	return false
}

func (x *ChatRequest) GetKbIds() []string {
	if x != nil {
		return x.KbIds
	}
	return nil
}

func (x *ChatRequest) GetUseMemory() bool {
	if x != nil {
		return x.UseMemory
	}
	return false
}

func (x *ChatRequest) GetUseTools() bool {
	if x != nil {
		return x.UseTools
	}
	return false
}

func (x *ChatRequest) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *ChatRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetTopK() int32 {
	if x != nil && x.TopK != nil {
		return *x.TopK
	}
	return 0
}

func (x *ChatRequest) GetRerankTopN() int32 {
	if x != nil && x.RerankTopN != nil {
		return *x.RerankTopN
	}
	return 0
}

func (x *ChatRequest) GetScoreThreshold() float64 {
	if x != nil && x.ScoreThreshold != nil {
		return *x.ScoreThreshold
	}
	return 0
}

func (x *ChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ChatResponse 是一次非流式对话的输出。
//
// 字段与 `chat.py::ChatResponse` 逐条对应 —— **包括 `answer` 这个名字**：
// 契约里回答正文就叫 `answer`，网关落库时映射到消息台账的 `content`。
// 生成代码时若顺手改成 `content`，两侧的字段快照测试会立刻失败。
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完整回答（Markdown）。
	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	// AI 侧回的会话 ID。网关 MUST 校验它与请求一致；不一致时以网关的为准并告警
	// （接缝 J4 / AC-ORCH-07）。
	ConversationId *string `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	// 本条回答的 ID（AI 侧生成，用于排障对齐；网关自己的消息 ID 另生成）。
	MessageId  string           `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	References []*Reference     `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	ToolCalls  []*ToolCallTrace `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Usage      *Usage           `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	// stop / length / max_steps
	FinishReason string `protobuf:"bytes,7,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	// **实际**使用的上游模型名（不是请求里那个）。
	Model    string `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	Degraded bool   `protobuf:"varint,9,opt,name=degraded,proto3" json:"degraded,omitempty"`
	// rag_unavailable / memory_unavailable / rerank_skipped / mcp_unavailable / summary_failed
	DegradedReasons []string `protobuf:"bytes,10,rep,name=degraded_reasons,json=degradedReasons,proto3" json:"degraded_reasons,omitempty"`
	ElapsedMs       int64    `protobuf:"varint,11,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ChatResponse) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *ChatResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatResponse) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *ChatResponse) GetToolCalls() []*ToolCallTrace {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *ChatResponse) GetDegradedReasons() []string {
	if x != nil {
		return x.DegradedReasons
	}
	return nil
}

func (x *ChatResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

// Reference 是回答里的引用来源（`docs/06` §6）。
type Reference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 与正文里的 [n] 一一对应。
	Index         int32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ChunkId       string  `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocId         string  `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	KbId          string  `protobuf:"bytes,4,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	DocName       string  `protobuf:"bytes,5,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"`
	Page          *int32  `protobuf:"varint,6,opt,name=page,proto3,oneof" json:"page,omitempty"`
	HeadingPath   *string `protobuf:"bytes,7,opt,name=heading_path,json=headingPath,proto3,oneof" json:"heading_path,omitempty"`
	Score         float64 `protobuf:"fixed64,8,opt,name=score,proto3" json:"score,omitempty"`
	Snippet       string  `protobuf:"bytes,9,opt,name=snippet,proto3" json:"snippet,omitempty"`
	ContentSha256 string  `protobuf:"bytes,10,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *Reference) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Reference) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Reference) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Reference) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *Reference) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *Reference) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *Reference) GetHeadingPath() string {
	if x != nil && x.HeadingPath != nil {
		return *x.HeadingPath
	}
	return ""
}

func (x *Reference) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Reference) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Reference) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

// ToolCallTrace 是一条工具调用轨迹。
type ToolCallTrace struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 实际执行参数。proto3 没有「任意 JSON」类型，用 JSON **字符串**承载
	// （与 docs/04-§2.3 的事件映射表同口径）。网关落库时按字节存进
	// `tool_calls` 列，不解析 —— schema 由 AI 侧定义。
	ArgumentsJson string `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// ok / error / timeout / forbidden
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary       string `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	ElapsedMs     int64  `protobuf:"varint,6,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallTrace) Reset() {
	*x = ToolCallTrace{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallTrace) ProtoMessage() {}

func (x *ToolCallTrace) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallTrace.ProtoReflect.Descriptor instead.
func (*ToolCallTrace) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallTrace) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallTrace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallTrace) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolCallTrace) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolCallTrace) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ToolCallTrace) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

// Usage 是本次对话的 token 用量。
type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int64                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *Usage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// ChatEvent 是一条流式事件（对应 HTTP SSE 的一帧）。
type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatEvent_Meta
	//	*ChatEvent_Reference
	//	*ChatEvent_Token
	//	*ChatEvent_ToolCall
	//	*ChatEvent_ToolResult
	//	*ChatEvent_Usage
	//	*ChatEvent_Error
	//	*ChatEvent_Done
	//	*ChatEvent_Unknown
	Event         isChatEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ChatEvent) GetEvent() isChatEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatEvent) GetMeta() *StreamMeta {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *ChatEvent) GetReference() *StreamReferences {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Reference); ok {
			return x.Reference
		}
	}
	return nil
}

func (x *ChatEvent) GetToken() *StreamToken {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *ChatEvent) GetToolCall() *StreamToolCall {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ChatEvent) GetToolResult() *StreamToolResult {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ChatEvent) GetUsage() *Usage {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *ChatEvent) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ChatEvent) GetDone() *StreamDone {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ChatEvent) GetUnknown() *StreamUnknown {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Unknown); ok {
			return x.Unknown
		}
	}
	return nil
}

type isChatEvent_Event interface {
	isChatEvent_Event()
}

type ChatEvent_Meta struct {
	Meta *StreamMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type ChatEvent_Reference struct {
	Reference *StreamReferences `protobuf:"bytes,2,opt,name=reference,proto3,oneof"`
}

type ChatEvent_Token struct {
	Token *StreamToken `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type ChatEvent_ToolCall struct {
	ToolCall *StreamToolCall `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ChatEvent_ToolResult struct {
	ToolResult *StreamToolResult `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ChatEvent_Usage struct {
	// 复用非流式的 `Usage`：字段与 HTTP 版 `usage` 事件的 data 完全一致，
	// 再造一个同字段的 message 只会多一处要同步的地方。
	Usage *Usage `protobuf:"bytes,6,opt,name=usage,proto3,oneof"`
}

type ChatEvent_Error struct {
	Error *StreamError `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type ChatEvent_Done struct {
	Done *StreamDone `protobuf:"bytes,8,opt,name=done,proto3,oneof"`
}

type ChatEvent_Unknown struct {
	Unknown *StreamUnknown `protobuf:"bytes,9,opt,name=unknown,proto3,oneof"`
}

func (*ChatEvent_Meta) isChatEvent_Event() {}

func (*ChatEvent_Reference) isChatEvent_Event() {}

func (*ChatEvent_Token) isChatEvent_Event() {}

func (*ChatEvent_ToolCall) isChatEvent_Event() {}

func (*ChatEvent_ToolResult) isChatEvent_Event() {}

func (*ChatEvent_Usage) isChatEvent_Event() {}

func (*ChatEvent_Error) isChatEvent_Event() {}

func (*ChatEvent_Done) isChatEvent_Event() {}

func (*ChatEvent_Unknown) isChatEvent_Event() {}

// StreamMeta 是首帧（对应 SSE 的 `event: meta`）。
type StreamMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AI 侧回显的会话 ID。网关 MUST 校验它与请求一致（接缝 J4 / AC-ORCH-07）。
	ConversationId *string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	// AI 侧生成本条回答的 ID（网关自己的消息 ID 另生成，两者都记下来便于排障对齐）。
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// **实际**使用的模型名。
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// RFC3339 毫秒 UTC。
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 本轮是否发生降级（RAG/记忆）。
	Degraded bool `protobuf:"varint,5,opt,name=degraded,proto3" json:"degraded,omitempty"`
	// 降级原因列表（RAG/记忆 各自的降级理由）。
	//
	// 这里比 HTTP 版 `meta` 多一个字段，是**有意**的：docs/04-§2.3 的映射表只列了
	// `degraded` 布尔，而 docs/04-§9 要求「AI 返回 degraded=true 时在 assistant 消息的
	// `degraded_reasons` 中保留」—— 只传布尔值满足不了那一条。AI 侧本来就有
	// `prepared.degraded_reasons`，把原因一起带过来是零成本的。
	DegradedReasons []string `protobuf:"bytes,6,rep,name=degraded_reasons,json=degradedReasons,proto3" json:"degraded_reasons,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamMeta) Reset() {
	*x = StreamMeta{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMeta) ProtoMessage() {}

func (x *StreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMeta.ProtoReflect.Descriptor instead.
func (*StreamMeta) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *StreamMeta) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *StreamMeta) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *StreamMeta) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamMeta) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StreamMeta) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *StreamMeta) GetDegradedReasons() []string {
	if x != nil {
		return x.DegradedReasons
	}
	return nil
}

// StreamReferences 是引用帧（对应 SSE 的 `event: reference`）。
//
// 一次给出**本轮全部**引用（而不是增量）：契约要求引用先于首个 token 推送，
// 而正文里的 `[n]` 需要客户端在拼接时就能查到 `n` 对应的来源。
//
// 本帧**可以出现多次**（Agent 路径在每次 tool_result 之后补发一次，因为新检索到的
// 片段是在那一轮才产生的）。语义是「当前引用集合」而不是「新增引用」，
// 因此消费方 MUST 整体替换、MUST NOT 追加 —— 追加会让同一条引用重复落库，
// 而正文里的 `[1]` 只指向其中一个。
type StreamReferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	References    []*Reference           `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReferences) Reset() {
	*x = StreamReferences{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReferences) ProtoMessage() {}

func (x *StreamReferences) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReferences.ProtoReflect.Descriptor instead.
func (*StreamReferences) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *StreamReferences) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

// StreamToken 是正文增量帧（对应 SSE 的 `event: token`）。
type StreamToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 增量文本。**可能为空串**（上游有时会发空 delta），空串也必须原样透传：
	// 丢弃它会让客户端与服务端的帧数不一致，而 docs/04-§4.1 要求顺序与数量保真。
	Delta         string `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamToken) Reset() {
	*x = StreamToken{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamToken) ProtoMessage() {}

func (x *StreamToken) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamToken.ProtoReflect.Descriptor instead.
func (*StreamToken) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *StreamToken) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

// StreamToolCall 是工具调用开始帧（对应 SSE 的 `event: tool_call`）。
type StreamToolCall struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 与 `ToolCallTrace.arguments_json` 同口径：proto3 没有「任意 JSON」类型，
	// 用 JSON 字符串承载，网关按字节存。
	ArgumentsJson string `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamToolCall) Reset() {
	*x = StreamToolCall{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamToolCall) ProtoMessage() {}

func (x *StreamToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamToolCall.ProtoReflect.Descriptor instead.
func (*StreamToolCall) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *StreamToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *StreamToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// StreamToolResult 是工具调用结果帧（对应 SSE 的 `event: tool_result`）。
//
// 与 `StreamToolCall` 靠 `call_id` 配对：网关落库时要拼成一条完整轨迹
// （`docs/03-§4.1` 的 `tool_calls` 数组），只有开始没有结果的调用
// 落库时 `status` 取 `error`（`summary` 说明「未返回结果」）。
type StreamToolResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// ok / error / timeout / forbidden
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Summary       string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	ElapsedMs     int64  `protobuf:"varint,5,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamToolResult) Reset() {
	*x = StreamToolResult{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamToolResult) ProtoMessage() {}

func (x *StreamToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamToolResult.ProtoReflect.Descriptor instead.
func (*StreamToolResult) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *StreamToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *StreamToolResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamToolResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamToolResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *StreamToolResult) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

// StreamError 是错误帧（对应 SSE 的 `event: error`）。
//
// 与 `AiError`（错误信封，挂在 `google.rpc.Status.details` 上）**不是一回事**：
// `AiError` 用于「响应头都还没发出」的失败，`StreamError` 用于「流已经开始推、
// 只能靠事件告知」的失败。两者的字段刻意保持同一套（code/message/retryable），
// 客户端可以用同一段分支处理。
type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *StreamError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// StreamDone 是结束帧（对应 SSE 的 `event: done`）。
type StreamDone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stop / length / max_steps / canceled
	FinishReason string `protobuf:"bytes,1,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	ElapsedMs    int64  `protobuf:"varint,2,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	// 本轮是否**提前结束**（上游超时/取消），即 `docs/03-§4.1` 的 `status=partial`。
	Partial       bool `protobuf:"varint,3,opt,name=partial,proto3" json:"partial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDone) Reset() {
	*x = StreamDone{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDone) ProtoMessage() {}

func (x *StreamDone) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDone.ProtoReflect.Descriptor instead.
func (*StreamDone) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *StreamDone) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *StreamDone) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *StreamDone) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

// StreamUnknown 是未识别事件的逃逸口（docs/04-§4.1「未知事件 MUST 透传」）。
type StreamUnknown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原始 SSE `event:` 名。
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// 原始 `data` 的 JSON 字节。网关不解析、不再序列化，原样转发。
	DataJson      []byte `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUnknown) Reset() {
	*x = StreamUnknown{}
	mi := &file_aiplatform_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUnknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUnknown) ProtoMessage() {}

func (x *StreamUnknown) ProtoReflect() protoreflect.Message {
	mi := &file_aiplatform_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUnknown.ProtoReflect.Descriptor instead.
func (*StreamUnknown) Descriptor() ([]byte, []int) {
	return file_aiplatform_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *StreamUnknown) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StreamUnknown) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

var File_aiplatform_v1_chat_proto protoreflect.FileDescriptor

const file_aiplatform_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18aiplatform/v1/chat.proto\x12\raiplatform.v1\"\xb4\x01\n" +
	"\aAiError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vhttp_status\x18\x03 \x01(\x05R\n" +
	"httpStatus\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12!\n" +
	"\fdetails_json\x18\x06 \x01(\tR\vdetailsJson\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x84\x05\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12,\n" +
	"\x0fconversation_id\x18\x02 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x124\n" +
	"\ahistory\x18\x03 \x03(\v2\x1a.aiplatform.v1.ChatMessageR\ahistory\x12\x17\n" +
	"\ause_rag\x18\x04 \x01(\bR\x06useRag\x12\x15\n" +
	"\x06kb_ids\x18\x05 \x03(\tR\x05kbIds\x12\x1d\n" +
	"\n" +
	"use_memory\x18\x06 \x01(\bR\tuseMemory\x12\x1b\n" +
	"\tuse_tools\x18\a \x01(\bR\buseTools\x12\x19\n" +
	"\x05model\x18\b \x01(\tH\x01R\x05model\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\t \x01(\x01H\x02R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_k\x18\n" +
	" \x01(\x05H\x03R\x04topK\x88\x01\x01\x12%\n" +
	"\frerank_top_n\x18\v \x01(\x05H\x04R\n" +
	"rerankTopN\x88\x01\x01\x12,\n" +
	"\x0fscore_threshold\x18\f \x01(\x01H\x05R\x0escoreThreshold\x88\x01\x01\x12D\n" +
	"\bmetadata\x18\r \x03(\v2(.aiplatform.v1.ChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_conversation_idB\b\n" +
	"\x06_modelB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_kB\x0f\n" +
	"\r_rerank_top_nB\x12\n" +
	"\x10_score_threshold\"\xcb\x03\n" +
	"\fChatResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12,\n" +
	"\x0fconversation_id\x18\x02 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x128\n" +
	"\n" +
	"references\x18\x04 \x03(\v2\x18.aiplatform.v1.ReferenceR\n" +
	"references\x12;\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x1c.aiplatform.v1.ToolCallTraceR\ttoolCalls\x12*\n" +
	"\x05usage\x18\x06 \x01(\v2\x14.aiplatform.v1.UsageR\x05usage\x12#\n" +
	"\rfinish_reason\x18\a \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x1a\n" +
	"\bdegraded\x18\t \x01(\bR\bdegraded\x12)\n" +
	"\x10degraded_reasons\x18\n" +
	" \x03(\tR\x0fdegradedReasons\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\v \x01(\x03R\telapsedMsB\x12\n" +
	"\x10_conversation_id\"\xb5\x02\n" +
	"\tReference\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\x12\x13\n" +
	"\x05kb_id\x18\x04 \x01(\tR\x04kbId\x12\x19\n" +
	"\bdoc_name\x18\x05 \x01(\tR\adocName\x12\x17\n" +
	"\x04page\x18\x06 \x01(\x05H\x00R\x04page\x88\x01\x01\x12&\n" +
	"\fheading_path\x18\a \x01(\tH\x01R\vheadingPath\x88\x01\x01\x12\x14\n" +
	"\x05score\x18\b \x01(\x01R\x05score\x12\x18\n" +
	"\asnippet\x18\t \x01(\tR\asnippet\x12%\n" +
	"\x0econtent_sha256\x18\n" +
	" \x01(\tR\rcontentSha256B\a\n" +
	"\x05_pageB\x0f\n" +
	"\r_heading_path\"\xb4\x01\n" +
	"\rToolCallTrace\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x06 \x01(\x03R\telapsedMs\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\"\x89\x04\n" +
	"\tChatEvent\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.aiplatform.v1.StreamMetaH\x00R\x04meta\x12?\n" +
	"\treference\x18\x02 \x01(\v2\x1f.aiplatform.v1.StreamReferencesH\x00R\treference\x122\n" +
	"\x05token\x18\x03 \x01(\v2\x1a.aiplatform.v1.StreamTokenH\x00R\x05token\x12<\n" +
	"\ttool_call\x18\x04 \x01(\v2\x1d.aiplatform.v1.StreamToolCallH\x00R\btoolCall\x12B\n" +
	"\vtool_result\x18\x05 \x01(\v2\x1f.aiplatform.v1.StreamToolResultH\x00R\n" +
	"toolResult\x12,\n" +
	"\x05usage\x18\x06 \x01(\v2\x14.aiplatform.v1.UsageH\x00R\x05usage\x122\n" +
	"\x05error\x18\a \x01(\v2\x1a.aiplatform.v1.StreamErrorH\x00R\x05error\x12/\n" +
	"\x04done\x18\b \x01(\v2\x19.aiplatform.v1.StreamDoneH\x00R\x04done\x128\n" +
	"\aunknown\x18\t \x01(\v2\x1c.aiplatform.v1.StreamUnknownH\x00R\aunknownB\a\n" +
	"\x05event\"\xe9\x01\n" +
	"\n" +
	"StreamMeta\x12,\n" +
	"\x0fconversation_id\x18\x01 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\bdegraded\x18\x05 \x01(\bR\bdegraded\x12)\n" +
	"\x10degraded_reasons\x18\x06 \x03(\tR\x0fdegradedReasonsB\x12\n" +
	"\x10_conversation_id\"L\n" +
	"\x10StreamReferences\x128\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\x18.aiplatform.v1.ReferenceR\n" +
	"references\"#\n" +
	"\vStreamToken\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\"d\n" +
	"\x0eStreamToolCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"\x90\x01\n" +
	"\x10StreamToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x05 \x01(\x03R\telapsedMs\"Y\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"j\n" +
	"\n" +
	"StreamDone\x12#\n" +
	"\rfinish_reason\x18\x01 \x01(\tR\ffinishReason\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x02 \x01(\x03R\telapsedMs\x12\x18\n" +
	"\apartial\x18\x03 \x01(\bR\apartial\"B\n" +
	"\rStreamUnknown\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson2\x93\x01\n" +
	"\n" +
	"AiPlatform\x12?\n" +
	"\x04Chat\x12\x1a.aiplatform.v1.ChatRequest\x1a\x1b.aiplatform.v1.ChatResponse\x12D\n" +
	"\n" +
	"ChatStream\x12\x1a.aiplatform.v1.ChatRequest\x1a\x18.aiplatform.v1.ChatEvent0\x01BQZOgithub.com/YunfeiSHU/ai-assistant/ai-platform-go/api/aiplatform/v1;aiplatformv1b\x06proto3"

var (
	file_aiplatform_v1_chat_proto_rawDescOnce sync.Once
	file_aiplatform_v1_chat_proto_rawDescData []byte
)

func file_aiplatform_v1_chat_proto_rawDescGZIP() []byte {
	file_aiplatform_v1_chat_proto_rawDescOnce.Do(func() {
		file_aiplatform_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aiplatform_v1_chat_proto_rawDesc), len(file_aiplatform_v1_chat_proto_rawDesc)))
	})
	return file_aiplatform_v1_chat_proto_rawDescData
}

var file_aiplatform_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_aiplatform_v1_chat_proto_goTypes = []any{
	(*AiError)(nil),          // 0: aiplatform.v1.AiError
	(*ChatMessage)(nil),      // 1: aiplatform.v1.ChatMessage
	(*ChatRequest)(nil),      // 2: aiplatform.v1.ChatRequest
	(*ChatResponse)(nil),     // 3: aiplatform.v1.ChatResponse
	(*Reference)(nil),        // 4: aiplatform.v1.Reference
	(*ToolCallTrace)(nil),    // 5: aiplatform.v1.ToolCallTrace
	(*Usage)(nil),            // 6: aiplatform.v1.Usage
	(*ChatEvent)(nil),        // 7: aiplatform.v1.ChatEvent
	(*StreamMeta)(nil),       // 8: aiplatform.v1.StreamMeta
	(*StreamReferences)(nil), // 9: aiplatform.v1.StreamReferences
	(*StreamToken)(nil),      // 10: aiplatform.v1.StreamToken
	(*StreamToolCall)(nil),   // 11: aiplatform.v1.StreamToolCall
	(*StreamToolResult)(nil), // 12: aiplatform.v1.StreamToolResult
	(*StreamError)(nil),      // 13: aiplatform.v1.StreamError
	(*StreamDone)(nil),       // 14: aiplatform.v1.StreamDone
	(*StreamUnknown)(nil),    // 15: aiplatform.v1.StreamUnknown
	nil,                      // 16: aiplatform.v1.ChatRequest.MetadataEntry
}
var file_aiplatform_v1_chat_proto_depIdxs = []int32{
	1,  // 0: aiplatform.v1.ChatRequest.history:type_name -> aiplatform.v1.ChatMessage
	16, // 1: aiplatform.v1.ChatRequest.metadata:type_name -> aiplatform.v1.ChatRequest.MetadataEntry
	4,  // 2: aiplatform.v1.ChatResponse.references:type_name -> aiplatform.v1.Reference
	5,  // 3: aiplatform.v1.ChatResponse.tool_calls:type_name -> aiplatform.v1.ToolCallTrace
	6,  // 4: aiplatform.v1.ChatResponse.usage:type_name -> aiplatform.v1.Usage
	8,  // 5: aiplatform.v1.ChatEvent.meta:type_name -> aiplatform.v1.StreamMeta
	9,  // 6: aiplatform.v1.ChatEvent.reference:type_name -> aiplatform.v1.StreamReferences
	10, // 7: aiplatform.v1.ChatEvent.token:type_name -> aiplatform.v1.StreamToken
	11, // 8: aiplatform.v1.ChatEvent.tool_call:type_name -> aiplatform.v1.StreamToolCall
	12, // 9: aiplatform.v1.ChatEvent.tool_result:type_name -> aiplatform.v1.StreamToolResult
	6,  // 10: aiplatform.v1.ChatEvent.usage:type_name -> aiplatform.v1.Usage
	13, // 11: aiplatform.v1.ChatEvent.error:type_name -> aiplatform.v1.StreamError
	14, // 12: aiplatform.v1.ChatEvent.done:type_name -> aiplatform.v1.StreamDone
	15, // 13: aiplatform.v1.ChatEvent.unknown:type_name -> aiplatform.v1.StreamUnknown
	4,  // 14: aiplatform.v1.StreamReferences.references:type_name -> aiplatform.v1.Reference
	2,  // 15: aiplatform.v1.AiPlatform.Chat:input_type -> aiplatform.v1.ChatRequest
	2,  // 16: aiplatform.v1.AiPlatform.ChatStream:input_type -> aiplatform.v1.ChatRequest
	3,  // 17: aiplatform.v1.AiPlatform.Chat:output_type -> aiplatform.v1.ChatResponse
	7,  // 18: aiplatform.v1.AiPlatform.ChatStream:output_type -> aiplatform.v1.ChatEvent
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_aiplatform_v1_chat_proto_init() }
func file_aiplatform_v1_chat_proto_init() {
	if File_aiplatform_v1_chat_proto != nil {
		return
	}
	file_aiplatform_v1_chat_proto_msgTypes[2].OneofWrappers = []any{}
	file_aiplatform_v1_chat_proto_msgTypes[3].OneofWrappers = []any{}
	file_aiplatform_v1_chat_proto_msgTypes[4].OneofWrappers = []any{}
	file_aiplatform_v1_chat_proto_msgTypes[7].OneofWrappers = []any{
		(*ChatEvent_Meta)(nil),
		(*ChatEvent_Reference)(nil),
		(*ChatEvent_Token)(nil),
		(*ChatEvent_ToolCall)(nil),
		(*ChatEvent_ToolResult)(nil),
		(*ChatEvent_Usage)(nil),
		(*ChatEvent_Error)(nil),
		(*ChatEvent_Done)(nil),
		(*ChatEvent_Unknown)(nil),
	}
	file_aiplatform_v1_chat_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aiplatform_v1_chat_proto_rawDesc), len(file_aiplatform_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aiplatform_v1_chat_proto_goTypes,
		DependencyIndexes: file_aiplatform_v1_chat_proto_depIdxs,
		MessageInfos:      file_aiplatform_v1_chat_proto_msgTypes,
	}.Build()
	File_aiplatform_v1_chat_proto = out.File
	file_aiplatform_v1_chat_proto_goTypes = nil
	file_aiplatform_v1_chat_proto_depIdxs = nil
}
