// ai-platform 的 gRPC 契约（网关 → AI，内网调用）。
//
// ============================================================================
// 这是**契约真源**（接缝 J5），两侧都从这一个文件生成代码：
//   - Go 侧：`api/aiplatform/v1/*.pb.go`（网关的 client）
//   - Python 侧：`app/grpc/aiplatform/v1/*_pb2*.py`（AI 的 server）
// 字段名/类型/必填性一旦漂移，两侧的字段级快照测试会直接失败（AC-ORCH-02）。
//
// 为什么真源放在 `ai-platform-go/proto/` 而不是父仓库根：
//   网关是这份契约的所有者（docs/04 是网关的 SRS，AI 侧按其实现），
//   放在网关模块内让「改契约 → 重新生成 → 编译」在同一个模块里完成，
//   不依赖模块外的相对路径。AI 侧的生成脚本显式指向这个文件（见其 tools/）。
//
// 为什么**只**定义 gRPC，不写 `option (google.api.http)`：
//   网关对外是 Gin HTTP/SSE，**不打算**用 kratos 的 HTTP 注解 —— 带上它会让这份
//   契约多依赖 `google/api/annotations.proto`（要额外维护 third_party/），
//   而对外 HTTP 契约的真源是 `docs/02`/`docs/03` 与 Pydantic 模型（OpenAPI）。
//   一份契约只管一个方向，两边都清楚「谁是真源」。
//
// 传输分工（docs/08-§7 的架构决策）：
//   - `Chat` / `ChatStream` 走 gRPC（本文件，M3 落 `Chat`、M4 落 `ChatStream`）；
//   - KB / 文档 / 任务 / 上下文摘要等**纯透传**接口走 HTTP（docs/04-§7）。
// ============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: aiplatform/v1/chat.proto

package aiplatformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiPlatform_Chat_FullMethodName       = "/aiplatform.v1.AiPlatform/Chat"
	AiPlatform_ChatStream_FullMethodName = "/aiplatform.v1.AiPlatform/ChatStream"
)

// AiPlatformClient is the client API for AiPlatform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AiPlatform 是 AI 侧的内网服务。
type AiPlatformClient interface {
	// Chat 一次完整的非流式对话（docs/04-§2.2 的 `POST /chat`）。
	//
	// 与 HTTP `POST /chat` **行为等价**（含 `use_tools=true` 时转 Agent 流程），
	// 两侧的差别只有传输：HTTP 用 `Authorization` 头，gRPC 用同名 metadata。
	//
	// MUST NOT 重试（docs/04-§3.4）：会重复计费、重复落上下文。
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// ChatStream 一次流式对话（docs/04-§2.2 的 `POST /chat/stream` 的等价物）。
	//
	// 事件序列（docs/04-§2.3）：`meta` → `reference`* → (`tool_call`/`tool_result`)*
	// → `token`* → `usage` → `done`；出错时以 `error` 收尾且**不再有** `usage`/`done`。
	//
	// 与 HTTP SSE 版本的差别只有传输：HTTP 版把每个事件序列化成
	// `event: <名>\ndata: <JSON>\n\n`，这里把同一份数据放进 `ChatEvent` 的 oneof。
	//
	// MUST NOT 重试（同上）。客户端取消（断连）时 AI 侧 MUST 停止上游 LLM 调用
	// （REQ-ORCH-004 / 其 SRS 的 REQ-CHAT-006）。
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
}

type aiPlatformClient struct {
	cc grpc.ClientConnInterface
}

func NewAiPlatformClient(cc grpc.ClientConnInterface) AiPlatformClient {
	return &aiPlatformClient{cc}
}

func (c *aiPlatformClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, AiPlatform_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiPlatformClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiPlatform_ServiceDesc.Streams[0], AiPlatform_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiPlatform_ChatStreamClient = grpc.ServerStreamingClient[ChatEvent]

// AiPlatformServer is the server API for AiPlatform service.
// All implementations must embed UnimplementedAiPlatformServer
// for forward compatibility.
//
// AiPlatform 是 AI 侧的内网服务。
type AiPlatformServer interface {
	// Chat 一次完整的非流式对话（docs/04-§2.2 的 `POST /chat`）。
	//
	// 与 HTTP `POST /chat` **行为等价**（含 `use_tools=true` 时转 Agent 流程），
	// 两侧的差别只有传输：HTTP 用 `Authorization` 头，gRPC 用同名 metadata。
	//
	// MUST NOT 重试（docs/04-§3.4）：会重复计费、重复落上下文。
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// ChatStream 一次流式对话（docs/04-§2.2 的 `POST /chat/stream` 的等价物）。
	//
	// 事件序列（docs/04-§2.3）：`meta` → `reference`* → (`tool_call`/`tool_result`)*
	// → `token`* → `usage` → `done`；出错时以 `error` 收尾且**不再有** `usage`/`done`。
	//
	// 与 HTTP SSE 版本的差别只有传输：HTTP 版把每个事件序列化成
	// `event: <名>\ndata: <JSON>\n\n`，这里把同一份数据放进 `ChatEvent` 的 oneof。
	//
	// MUST NOT 重试（同上）。客户端取消（断连）时 AI 侧 MUST 停止上游 LLM 调用
	// （REQ-ORCH-004 / 其 SRS 的 REQ-CHAT-006）。
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	mustEmbedUnimplementedAiPlatformServer()
}

// UnimplementedAiPlatformServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiPlatformServer struct{}

func (UnimplementedAiPlatformServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAiPlatformServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedAiPlatformServer) mustEmbedUnimplementedAiPlatformServer() {}
func (UnimplementedAiPlatformServer) testEmbeddedByValue()                    {}

// UnsafeAiPlatformServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiPlatformServer will
// result in compilation errors.
type UnsafeAiPlatformServer interface {
	mustEmbedUnimplementedAiPlatformServer()
}

func RegisterAiPlatformServer(s grpc.ServiceRegistrar, srv AiPlatformServer) {
	// If the following call pancis, it indicates UnimplementedAiPlatformServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiPlatform_ServiceDesc, srv)
}

func _AiPlatform_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiPlatformServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiPlatform_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiPlatformServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiPlatform_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiPlatformServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiPlatform_ChatStreamServer = grpc.ServerStreamingServer[ChatEvent]

// AiPlatform_ServiceDesc is the grpc.ServiceDesc for AiPlatform service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiPlatform_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiplatform.v1.AiPlatform",
	HandlerType: (*AiPlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _AiPlatform_Chat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _AiPlatform_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aiplatform/v1/chat.proto",
}
